# Generated by Django 4.0.6 on 2022-07-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_categories_competition_competitiongraphic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_code',
            new_name='Category_Code',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='CategoryName',
            new_name='Category_Name',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='CompetitionCategory',
            new_name='Competition_Category',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='CompetitionDetails',
            new_name='Competition_Details',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='CompetitionGraphic',
            new_name='Competition_Graphic',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='CompetitionTitle',
            new_name='Competition_Title',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='RegisteredUsers',
            new_name='Registered_Users',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='RegistrationEndDate',
            new_name='Registration_End_Date',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='RegistrationStartDate',
            new_name='Registration_Start_Date',
        ),
    ]
