# Generated by Django 4.0.6 on 2022-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_rename_category_code_categories_category_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='Slug',
            field=models.SlugField(default='competiton'),
        ),
    ]
