# Generated by Django 4.0.6 on 2022-07-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competition_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='Competition_Category',
        ),
        migrations.AddField(
            model_name='competition',
            name='Competition_Category',
            field=models.CharField(default='Web Development', max_length=255),
        ),
        migrations.AlterField(
            model_name='competition',
            name='Slug',
            field=models.SlugField(default='competiton', unique=True),
        ),
    ]
