# Generated by Django 4.0.6 on 2022-07-13 12:46

import competitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_competition_competition_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='competition',
            name='Registration_End_Date',
            field=models.DateField(validators=[competitions.models.CheckDateStart]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='Registration_Start_Date',
            field=models.DateField(validators=[competitions.models.CheckDateStart]),
        ),
    ]
